### ISSUE TITLE
TextService.FilterStringAsync wrong undefined return type

### ISSUE THREAD

**Issue by Felyrun** [roblox-ts/types#538]
API Reference (https://developer.roblox.com/en-us/api-reference/function/TextService/FilterStringAsync) says that TextService.FilterStringAsync returns a TextFilterResult (and not nil), but the return type here is TextFilterResult | undefined.

**Comment by Dionysusnu** [comment]
For reference, custom definition was first added in https://github.com/roblox-ts/types/commit/a3aa48d156a520d4d6c92dc2a92e7492d8aa15ed with no further type changes after that.

**Comment by osyrisrblx** [comment]
Actually it was https://github.com/roblox-ts/types/commit/7003fdd9ae90efc9236aeeacfac7393ff5db632f

**Comment by Validark** [comment]
Looks like I changed it by mistake? The [documentation from 2019](https://github.com/Validark/rbx-safe-types/blob/master-next/content/TextService/FilterStringAsync.md) is pretty much the same as it is today. I'm surprised no one noticed in 3 years.  I wonder if anyone wrote a check in their code to make sure the return result is defined because of these types, or would they just have used type assertions?

**Comment by Dionysusnu** [comment]
> I wonder if anyone wrote a check in their code to make sure the return result is defined because of these types, or would they just have used type assertions?

Considering this is an HTTP request and a critical part of user safety, I would say this is a good thing and have just kept the type with undefined, considering, as you say, no one ran into it for 3 years. Sometimes an overly restrictive type can be good for code style.

**Comment by Validark** [comment]
Well, if it's impossible for the API to return nil, there isn't any point to checking it. I don't see how it could be beneficial to write extra code and take up mental resources to deal with a situation that could never happen. I went ahead and changed it back to being always defined.
